version: "3.4"

services:
  homecooking-ui:
    image: ${DOCKER_REGISTRY-}homecooking-ui:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  homecooking-ui-dapr:
    image: "daprio/daprd:latest"
    command: ["./daprd", "-app-id", "homecooking-ui", "-app-port", "80"]
    depends_on:
      - homecooking-ui
    network_mode: "service:homecooking-ui"
