version: "3.4"

services:
  home-cooking-web:
    image: ${DOCKER_REGISTRY-}home-cooking-web:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  home-cooking-web-dapr:
    image: "daprio/daprd:latest"
    command: ["./daprd", "-app-id", "home-cooking-web", "-app-port", "80"]
    depends_on:
      - home-cooking-web
    network_mode: "service:home-cooking-web"
