version: '3.4'

services:
  home-cooking-react:
    image: ${DOCKER_REGISTRY-}home-cooking-react:prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '3000:80'

  # home-cooking-web-dapr:
  #   image: 'daprio/daprd:latest'
  #   command: ['./daprd', '-app-id', 'home-cooking-web', '-app-port', '80']
  #   depends_on:
  #     - home-cooking-react
  #   network_mode: 'service:home-cooking-react'
